In [1]:
import pandas as pd 
import numpy as np

In [2]:
#reading the uploaded data as a dataframe using pamdas (pd)
energy_data=pd.read_csv("energydata_complete.csv")

In [3]:
#exploring the first 5 roles of the data with zero indexing
energy_data.head()

,date,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3,T4,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,2016-01-11 17:00:00,60,30,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,2016-01-11 17:10:00,60,30,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,2016-01-11 17:20:00,50,30,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,2016-01-11 17:30:00,50,40,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,2016-01-11 17:40:00,60,40,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [4]:
#removing the date and lights columns 
q_data=energy_data.drop(columns=["date","lights"])

In [5]:
q_data.head()

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,60,19.89,47.596667,19.2,44.790000,19.79,44.730000,19.000000,45.566667,17.166667,...,17.033333,45.53,6.600000,733.5,92.0,7.000000,63.000000,5.3,13.275433,13.275433
1,60,19.89,46.693333,19.2,44.722500,19.79,44.790000,19.000000,45.992500,17.166667,...,17.066667,45.56,6.483333,733.6,92.0,6.666667,59.166667,5.2,18.606195,18.606195
2,50,19.89,46.300000,19.2,44.626667,19.79,44.933333,18.926667,45.890000,17.166667,...,17.000000,45.50,6.366667,733.7,92.0,6.333333,55.333333,5.1,28.642668,28.642668
3,50,19.89,46.066667,19.2,44.590000,19.79,45.000000,18.890000,45.723333,17.166667,...,17.000000,45.40,6.250000,733.8,92.0,6.000000,51.500000,5.0,45.410389,45.410389
4,60,19.89,46.333333,19.2,44.530000,19.79,45.000000,18.890000,45.530000,17.200000,...,17.000000,45.40,6.133333,733.9,92.0,5.666667,47.666667,4.9,10.084097,10.084097

In [6]:
#Some Exploratory data analysis on the q_data (the energy data without date and lights)
q_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19735 entries, 0 to 19734
Data columns (total 27 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Appliances   19735 non-null  int64
 1   T1           19735 non-null  float64
 2   RH_1         19735 non-null  float64
 3   T2           19735 non-null  float64
 4   RH_2         19735 non-null  float64
 5   T3           19735 non-null  float64
 6   RH_3         19735 non-null  float64
 7   T4           19735 non-null  float64
 8   RH_4         19735 non-null  float64
 9   T5           19735 non-null  float64
 10  RH_5         19735 non-null  float64
 11  T6           19735 non-null  float64
 12  RH_6         19735 non-null  float64
 13  T7           19735 non-null  float64
 14  RH_7         19735 non-null  float64
 15  T8           19735 non-null  float64
 16  RH_8         19735 non-null  float64
 17  T9           19735 non-null  float64
 18  RH_9         19735 non-null  float64
 19  T_out        19735 non-null  float64
 20  Press_mm_hg  19735 non-null  float64
 21  RH_out       19735 non-null  float64
 22  Windspeed    19735 non-null  float64
 23  Visibility   19735 non-null  float64
 24  Tdewpoint    19735 non-null  float64
 25  rv1          19735 non-null  float64
 26  rv2          19735 non-null  float64
dtypes: float64(26), int64(1)
memory usage: 4.1 MB

In [7]:
q_data.describe()

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
count,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,...,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000,19735.000000
mean,97.694958,21.686571,40.259739,20.341219,40.420420,22.267611,39.242500,20.855335,39.026904,19.592106,...,19.485828,41.552401,7.411665,755.522602,79.750418,4.039752,38.330834,3.760707,24.988033,24.988033
std,102.524891,1.606066,3.979299,2.192974,4.069813,2.006111,3.254576,2.042884,4.341321,1.844623,...,2.014712,4.151497,5.317409,7.399441,14.901088,2.451221,11.794719,4.194648,14.496634,14.496634
min,10.000000,16.790000,27.023333,16.100000,20.463333,17.200000,28.766667,15.100000,27.660000,15.330000,...,14.890000,29.166667,-5.000000,729.300000,24.000000,0.000000,1.000000,-6.600000,0.005322,0.005322
25%,50.000000,20.760000,37.333333,18.790000,37.900000,20.790000,36.900000,19.530000,35.530000,18.277500,...,18.000000,38.500000,3.666667,750.933333,70.333333,2.000000,29.000000,0.900000,12.497889,12.497889
50%,60.000000,21.600000,39.656667,20.000000,40.500000,22.100000,38.530000,20.666667,38.400000,19.390000,...,19.390000,40.900000,6.916667,756.100000,83.666667,3.666667,40.000000,3.433333,24.897653,24.897653
75%,100.000000,22.600000,43.066667,21.500000,43.260000,23.290000,41.760000,22.100000,42.156667,20.619643,...,20.600000,44.338095,10.408333,760.933333,91.666667,5.500000,40.000000,6.566667,37.583769,37.583769
max,1080.000000,26.260000,63.360000,29.856667,56.026667,29.236000,50.163333,26.200000,51.090000,25.795000,...,24.500000,53.326667,26.100000,772.300000,100.000000,14.000000,66.000000,15.500000,49.996530,49.996530

In [8]:
q_data.corr()

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
Appliances,1.000000,0.055447,0.086031,0.120073,-0.060465,0.085060,0.036292,0.040281,0.016965,0.019760,...,0.010010,-0.051462,0.099155,-0.034885,-0.152282,0.087122,0.000230,0.015353,-0.011145,-0.011145
T1,0.055447,1.000000,0.164006,0.836834,-0.002509,0.892402,-0.028550,0.877001,0.097861,0.885247,...,0.844777,0.071756,0.682846,-0.150574,-0.345481,-0.087654,-0.076210,0.571309,-0.006203,-0.006203
RH_1,0.086031,0.164006,1.000000,0.269839,0.797535,0.253230,0.844677,0.106180,0.880359,0.205797,...,0.115263,0.764001,0.340767,-0.293957,0.274126,0.204932,-0.021057,0.639106,-0.000699,-0.000699
T2,0.120073,0.836834,0.269839,1.000000,-0.165610,0.735245,0.121497,0.762066,0.231563,0.720550,...,0.675535,0.157346,0.792255,-0.133028,-0.505291,0.052495,-0.069721,0.582602,-0.011087,-0.011087
RH_2,-0.060465,-0.002509,0.797535,-0.165610,1.000000,0.137319,0.678326,-0.047304,0.721435,0.110409,...,0.054544,0.676467,0.033674,-0.255646,0.584911,0.069190,-0.005368,0.499152,0.006275,0.006275
T3,0.085060,0.892402,0.253230,0.735245,0.137319,1.000000,-0.011234,0.852778,0.122737,0.888169,...,0.901324,0.134602,0.699417,-0.189974,-0.281718,-0.100776,-0.102310,0.645886,-0.005194,-0.005194
RH_3,0.036292,-0.028550,0.844677,0.121497,0.678326,-0.011234,1.000000,-0.140457,0.898978,-0.050062,...,-0.195270,0.833538,0.118207,-0.233274,0.356192,0.263188,0.017041,0.414387,-0.000477,-0.000477
T4,0.040281,0.877001,0.106180,0.762066,-0.047304,0.852778,-0.140457,1.000000,-0.048650,0.871813,...,0.889439,-0.025549,0.663478,-0.075292,-0.388602,-0.185747,-0.104768,0.519471,-0.001815,-0.001815
RH_4,0.016965,0.097861,0.880359,0.231563,0.721435,0.122737,0.898978,-0.048650,1.000000,0.091812,...,-0.044518,0.856591,0.293289,-0.250748,0.336813,0.300192,0.002636,0.616509,-0.001787,-0.001787
T5,0.019760,0.885247,0.205797,0.720550,0.110409,0.888169,-0.050062,0.871813,0.091812,1.000000,...,0.911055,0.072308,0.651321,-0.170999,-0.273953,-0.145011,-0.084164,0.588362,-0.005490,-0.005490
RH_5,0.006955,-0.014782,0.303258,0.029595,0.250271,-0.066355,0.375422,-0.076489,0.352591,0.032786,...,-0.138509,0.272197,-0.053126,-0.119327,0.185941,0.082044,-0.013133,0.078175,-0.011056,-0.011056
T6,0.117638,0.654769,0.316141,0.801186,-0.009670,0.686882,0.076833,0.652350,0.259047,0.629161,...,0.667177,0.184424,0.974787,-0.141643,-0.569119,0.169185,-0.081313,0.764242,-0.015086,-0.015086
RH_6,-0.083178,-0.615045,0.245126,-0.580372,0.389933,-0.647672,0.514912,-0.703149,0.392178,-0.632384,...,-0.738940,0.391943,-0.641572,-0.065814,0.718587,0.098317,0.108705,-0.260417,0.011671,0.011671
T7,0.025801,0.838705,0.021397,0.663660,-0.051422,0.847374,-0.250090,0.877763,-0.131204,0.870624,...,0.944776,-0.077690,0.631293,-0.097724,-0.411213,-0.185892,-0.110089,0.466625,-0.003900,-0.003900
RH_7,-0.055642,0.135182,0.801122,0.229212,0.690584,0.172624,0.832685,0.043527,0.894301,0.148905,...,0.028055,0.858686,0.294199,-0.265850,0.378519,0.212979,-0.007184,0.641857,0.001820,0.001820
T8,0.039572,0.825413,-0.030053,0.578191,-0.041023,0.795283,-0.283228,0.796256,-0.167066,0.824981,...,0.869338,-0.156820,0.502842,-0.162855,-0.300438,-0.218876,-0.060098,0.391810,-0.003210,-0.003210
RH_8,-0.094039,-0.006441,0.736196,0.068534,0.679777,0.044427,0.828822,-0.095192,0.847259,0.016388,...,-0.113014,0.855812,0.117141,-0.225591,0.487355,0.202380,0.046178,0.501775,0.004480,0.004480
T9,0.010010,0.844777,0.115263,0.675535,0.054544,0.901324,-0.195270,0.889439,-0.044518,0.911055,...,1.000000,-0.008683,0.668220,-0.156828,-0.318848,-0.177756,-0.103915,0.581483,-0.001227,-0.001227
RH_9,-0.051462,0.071756,0.764001,0.157346,0.676467,0.134602,0.833538,-0.025549,0.856591,0.072308,...,-0.008683,1.000000,0.223270,-0.183739,0.359377,0.238655,0.008667,0.540328,-0.002955,-0.002955
T_out,0.099155,0.682846,0.340767,0.792255,0.033674,0.699417,0.118207,0.663478,0.293289,0.651321,...,0.668220,0.223270,1.000000,-0.143249,-0.574197,0.192936,-0.077367,0.790661,-0.015216,-0.015216
Press_mm_hg,-0.034885,-0.150574,-0.293957,-0.133028,-0.255646,-0.189974,-0.233274,-0.075292,-0.250748,-0.170999,...,-0.156828,-0.183739,-0.143249,1.000000,-0.092017,-0.235032,0.040315,-0.244098,0.000699,0.000699
RH_out,-0.152282,-0.345481,0.274126,-0.505291,0.584911,-0.281718,0.356192,-0.388602,0.336813,-0.273953,...,-0.318848,0.359377,-0.574197,-0.092017,1.000000,-0.176458,0.083125,0.036506,0.020441,0.020441
Windspeed,0.087122,-0.087654,0.204932,0.052495,0.069190,-0.100776,0.263188,-0.185747,0.300192,-0.145011,...,-0.177756,0.238655,0.192936,-0.235032,-0.176458,1.000000,-0.007516,0.125972,-0.011342,-0.011342
Visibility,0.000230,-0.076210,-0.021057,-0.069721,-0.005368,-0.102310,0.017041,-0.104768,0.002636,-0.084164,...,-0.103915,0.008667,-0.077367,0.040315,0.083125,-0.007516,1.000000,-0.042190,-0.005889,-0.005889
Tdewpoint,0.015353,0.571309,0.639106,0.582602,0.499152,0.645886,0.414387,0.519471,0.616509,0.588362,...,0.581483,0.540328,0.790661,-0.244098,0.036506,0.125972,-0.042190,1.000000,-0.003943,-0.003943
rv1,-0.011145,-0.006203,-0.000699,-0.011087,0.006275,-0.005194,-0.000477,-0.001815,-0.001787,-0.005490,...,-0.001227,-0.002955,-0.015216,0.000699,0.020441,-0.011342,-0.005889,-0.003943,1.000000,1.000000
rv2,-0.011145,-0.006203,-0.000699,-0.011087,0.006275,-0.005194,-0.000477,-0.001815,-0.001787,-0.005490,...,-0.001227,-0.002955,-0.015216,0.000699,0.020441,-0.011342,-0.005889,-0.003943,1.000000,1.000000

In [9]:
q_data.columns

Index(['Appliances', 'T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3', 'T4', 'RH_4',
       'T5', 'RH_5', 'T6', 'RH_6', 'T7', 'RH_7', 'T8', 'RH_8', 'T9', 'RH_9',
       'T_out', 'Press_mm_hg', 'RH_out', 'Windspeed', 'Visibility',
       'Tdewpoint', 'rv1', 'rv2'],
      dtype='object')

In [11]:
split_data = np.random.rand(len(energy_data)) < 0.8
train = q_data[split_data]
test = q_data[~split_data]

In [12]:
train

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
0,60,19.890000,47.596667,19.200000,44.790000,19.790000,44.730000,19.000000,45.566667,17.166667,...,17.033333,45.5300,6.600000,733.5,92.000000,7.000000,63.000000,5.300000,13.275433,13.275433
1,60,19.890000,46.693333,19.200000,44.722500,19.790000,44.790000,19.000000,45.992500,17.166667,...,17.066667,45.5600,6.483333,733.6,92.000000,6.666667,59.166667,5.200000,18.606195,18.606195
2,50,19.890000,46.300000,19.200000,44.626667,19.790000,44.933333,18.926667,45.890000,17.166667,...,17.000000,45.5000,6.366667,733.7,92.000000,6.333333,55.333333,5.100000,28.642668,28.642668
4,60,19.890000,46.333333,19.200000,44.530000,19.790000,45.000000,18.890000,45.530000,17.200000,...,17.000000,45.4000,6.133333,733.9,92.000000,5.666667,47.666667,4.900000,10.084097,10.084097
5,50,19.890000,46.026667,19.200000,44.500000,19.790000,44.933333,18.890000,45.730000,17.133333,...,17.000000,45.2900,6.016667,734.0,92.000000,5.333333,43.833333,4.800000,44.919484,44.919484
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19729,90,25.533333,46.860000,25.978000,42.534000,27.323333,41.090000,24.700000,45.626667,23.200000,...,23.200000,46.7450,22.866667,755.2,55.333333,3.166667,22.833333,13.366667,16.966162,16.966162
19730,100,25.566667,46.560000,25.890000,42.025714,27.200000,41.163333,24.700000,45.590000,23.200000,...,23.200000,46.7900,22.733333,755.2,55.666667,3.333333,23.666667,13.333333,43.096812,43.096812
19732,270,25.500000,46.596667,25.628571,42.768571,27.050000,41.690000,24.700000,45.730000,23.230000,...,23.200000,46.7900,22.466667,755.2,56.333333,3.666667,25.333333,13.266667,29.199117,29.199117
19733,420,25.500000,46.990000,25.414000,43.036000,26.890000,41.290000,24.700000,45.790000,23.200000,...,23.200000,46.8175,22.333333,755.2,56.666667,3.833333,26.166667,13.233333,6.322784,6.322784
19734,430,25.500000,46.600000,25.264286,42.971429,26.823333,41.156667,24.700000,45.963333,23.200000,...,23.200000,46.8450,22.200000,755.2,57.000000,4.000000,27.000000,13.200000,34.118851,34.118851

In [14]:
test.head()

,Appliances,T1,RH_1,T2,RH_2,T3,RH_3,T4,RH_4,T5,...,T9,RH_9,T_out,Press_mm_hg,RH_out,Windspeed,Visibility,Tdewpoint,rv1,rv2
3,50,19.890000,46.066667,19.200000,44.590000,19.79,45.000000,18.890000,45.723333,17.166667,...,17.00,45.400000,6.250000,733.800000,92.000000,6.0,51.5,5.000000,45.410389,45.410389
13,250,20.260000,52.726667,19.730000,45.100000,19.89,45.493333,19.000000,47.223333,17.100000,...,16.89,45.326667,6.000000,734.616667,90.500000,6.0,40.0,4.516667,19.205186,19.205186
24,110,21.133333,46.060000,20.426667,44.760000,20.29,46.433333,19.390000,48.193333,17.760000,...,16.89,44.966667,6.000000,735.400000,87.000000,6.0,40.0,3.900000,13.361033,13.361033
28,100,21.390000,45.690000,20.700000,45.060000,20.39,46.090000,19.426667,47.993333,18.666667,...,16.89,44.700000,5.733333,735.666667,87.666667,6.0,40.0,3.766667,43.484542,43.484542
42,40,21.390000,44.560000,20.790000,43.863333,20.20,45.663333,20.633333,46.790000,19.200000,...,16.89,45.700000,5.300000,736.900000,92.000000,6.0,22.0,4.100000,39.146638,39.146638

In [28]:
from sklearn import linear_model
regr=linear_model.LinearRegression()
train_x=np.asanyarray(train[['T2']])
train_y=np.asanyarray(train[['T6']])

regr.fit(train_x,train_y)
print ('Coefficients: ', regr.coef_)
print ('Intercept: ',regr.intercept_)

Coefficients:  [[2.22487846]]
Intercept:  [-37.35331409]

In [17]:
from sklearn.metrics import r2_score 
test_x = np.asanyarray(test[['T2']])
test_y = np.asanyarray(test[['T6']])
test_y_ = regr.predict(test_x)


print("Mean absolute error: %.2f" % np.mean(np.absolute(test_y_ - test_y)))
print("Residual sum of squares (MSE): %.2f" % np.mean((test_y_ - test_y) ** 2))
print("R2-score: %.2f" % r2_score(test_y , test_y_) )

Mean absolute error: 2.80
Residual sum of squares (MSE): 12.90
R2-score: 0.65

In [23]:
y_pred=regr.predict(test_y)

In [27]:
from sklearn.metrics import mean_squared_error
mean_squared_error(test_y,y_pred)

819.4421643651158

In [36]:
from sklearn.linear_model import Ridge 
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(train_x,train_y,test_size=0.3,random_state=42)

In [40]:
ridge=Ridge(alpha=0.4,normalize=True)
ridge.fit(train_x,train_y)
ridge_pred=ridge.predict(test_x)
ridge.score(test_x,test_y)

0.5957063444564321